<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Brand;

class BrandTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brandData=[
          [
              'name'=>'Apple',
          ],
            [
                'name'=>'Samsung',
            ],
            [
                'name'=>'Huawei',
            ],
            [
                'name'=>'Dell',
            ],
            [
                'name'=>'HP',
            ],
            [
                'name'=>'Lenovo',
            ],
            [
                'name'=>'Asus',
            ],
            [
                'name'=>'Acer',
            ],
            [
                'name'=>'Microsoft',
            ],
            [
                'name'=>'Google',
            ],
            [
                'name'=>'Razer',
            ],
            [
                'name'=>'Alienware',
            ],
            [
                'name'=>'MSI',
            ],
            [
                'name'=>'Sony',
            ],
            [
                'name'=>'Xiaomi',
            ],
            [
                'name'=>'OnePlus',
            ],
            [
                'name'=>'Nokia',
            ],
            [
                'name'=>'Motorola',
            ],
            [
                'name'=>'LG',
            ],
            [
                'name'=>'HTC',
            ],
            [
                'name'=>'BlackBerry',
            ],
            [
                'name'=>'Oppo',
            ],
            [
                'name'=>'Vivo',
            ],
            [
                'name'=>'Realme',
            ],
            [
                'name'=>'Infinix',
            ],
            [
                'name'=>'Tecno',
            ],
            [
                'name'=>'Symphony',
            ],
            [
                'name'=>'Walton',
            ],
            [
                'name'=>'Micromax',
            ],
            [
                'name'=>'Lava',
            ],
            [
                'name'=>'Maximus',
            ],
            [
                'name'=>'MyCell',
            ],
            [
                'name'=>'Samsung',
            ],
            [
                'name'=>'Transcend',
            ],
            [
                'name'=>'Kingston',
            ],
            [
                'name'=>'Western Digital',
            ],
            [
                'name'=>'Seagate',
            ],
            [
                'name'=>'Toshiba',
            ],
            [
                'name'=>'Sandisk',
            ],
            [
                'name'=>'Lexar',
            ],
            [
                'name'=>'Adata',
            ],
            [
                'name'=>'Apacer',
            ],
            [
                'name'=>'Patriot',
            ],
            [
                'name'=>'Gigabyte',
            ],
            [
                'name'=>'Corsair',
            ],
            [
                'name'=>'Crucial',
            ],
        ];

        foreach ($brandData as $brand){
            $findData = Brand::where('name',$brand['name'])->first();
            if(!$findData){
                Brand::create($brand);
            }
        }
    }
}